#!/usr/bin/env bash

LID_CLOSED=$(ioreg -r -k AppleClamshellState | grep AppleClamshellState | grep Yes)
if [ "$LID_CLOSED" ]; then
  EXTERNAL_DISPLAY_CONNECTED=$(pmset -g powerstate | grep AppleDisplay | grep USEABLE)
  if [ "$EXTERNAL_DISPLAY_CONNECTED" ]; then
    AWAKE=$(pmset -g powerstate | grep IODisplayWrangler | grep USEABLE)
    if [ "$AWAKE" ]; then
      pmset sleepnow
    fi
  fi

  NUM_DEVICE_PROXY=$(pmset -g powerstate | grep -c DCPDPDeviceProxy)
  NUM_SERVICE_PROXY=$(pmset -g powerstate | grep -c DCPDPServiceProxy)
  ARM_AWAKE=$(( 0 < NUM_DEVICE_PROXY && NUM_DEVICE_PROXY < 4 ||
        0 < NUM_SERVICE_PROXY && NUM_SERVICE_PROXY < 4 ))
  if [ "$ARM_AWAKE" ]; then
    pmset sleepnow
  fi
fi
